version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      ## The three lines below were initially commented out, however the build was failing so they needed to be included
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: UI tests - sudo pip install
          command: sudo pip install -U crcmod
      - run:
          name: UI tests - assembleDebug
          command: ./gradlew :app:assembleDebug -PdisablePreDex
      - store_artifacts:
          path: app/build/outputs/apk
      - run:
          name: UI tests - assembleAndroidTest
          command: ./gradlew :app:assembleAndroidTest -PdisablePreDex
      - store_artifacts:
          path: app/build/outputs/apk
      - run:
          name: UI tests - decode gcloud service key
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
      - run:
          name: UI tests - set project
          command: sudo gcloud config set project $GCLOUD_PROJECT
#      - run:
#          name: UI tests - update components
#          command: sudo gcloud --quiet components update
#      - run:
#          name: UI tests - install components beta
#          command: sudogcloud --quiet components install beta
      - run:
          name: UI tests - auth activate-service-account
          command: sudo gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run:
          name: UI tests - run
          command: echo "y" | sudo gcloud beta firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Nexus6,version=21,locale=en,orientation=portrait --results-bucket ci-android-test
      - run:
          name: UI tests - upload artifacts
          command: sudo gsutil -m cp -r -U `sudo gsutil ls gs://ci-android-test | tail -1` $CIRCLE_ARTIFACTS/
      - store_test_results:
          path: app/build/ui-test-results

